sensor_msgs/Image diff          # an image containing changes in height
geometry_msgs/Point32 position  # position in the real world where the terrain
                                # modification took place, position is the 
                                # center of the patch
float32 height                  # height of image in world units
float32 width                   # width of image in world units