geometry_msgs/Point32 position  # position in the real world, where x, y are at
                                # the center of circle
float32 outer_radius_a          # ellipse a outer radius
float32 inner_radius_a          # ellipse a inner radius
float32 outer_radius_b          # ellipse b outer radius
float32 inner_radius_b          # ellipse b inner radius
float32 angle                   # rotation angle of ellipse around z axis
                                # measured in degrees
float32 weight                  # weight of the operation on height values