bool use_defaults       # Set to true to use the default trench location
float32 x               # Trench starting point - X coordinate
float32 y               # Trench starting point - Y coordinate
float32 depth           # Desired depth
float32 length          # Desired length
float32 ground_position # Z coordinate of ground level in base_link frame
---
bool success
string message
