bool use_defaults       # Set to true to use the default grinding location
float32 x               # X coordinate of grinding starting point
float32 y               # Y coordinate of grinding starting point
float32 depth           # Desired depth
float32 length          # Desired length
float32 ground_position # Z coordinate of ground level in base_link frame
bool delete_prev_traj   # Set to true to cleanup ~/.ros
---
bool success
string message
