# goal definition
int32 frame
bool relative
geometry_msgs/Pose pose
float64 force_threshold
float64 torque_threshold
---
# result
geometry_msgs/Pose final_pose
float64 final_force
float64 final_torque
---
# feedback
geometry_msgs/Pose pose
float64 force
float64 torque
