#goal definition
int32 frame
bool relative
geometry_msgs/Point point
geometry_msgs/Vector3 normal
float64 depth
float64 length
---
# result
geometry_msgs/Point final     # arm final position
---
# feedback
geometry_msgs/Point current   # arm current position
