#goal definition
float32 x_delivery
float32 y_delivery
float32 z_delivery 
---
#result definition
float32 final_x
float32 final_y
float32 final_z
---
#feedback
float32 current_x
float32 current_y
float32 current_z
